# Site settings
title: Vegan Fat
email: vegan@fat.gr
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://vegan.fat.gr"
twitter_username: VeganFat

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
